echo Launching sleep 5 and sleep 10 in background... 
sleep 5 & sleep 10 &
echo Sleeping 2 seconds...
sleep 2
echo Calling 'jobs'
jobs
echo Sleeping 6 seconds...
sleep 6
echo Calling 'jobs'
jobs
echo Sleeping 3 seconds...
sleep 3
echo Calling 'jobs'
jobs
echo Calling 'jobs' again...
jobs
echo Exiting...
exit
